straw.spec:
- platform: num {ios,android}
- service.topic: string e.g. http
- type: enum {js,native}
- name: straw-{$platform}-{$topic}-service-{$type}
- dep-type: {cocoapods, wildpods, bower, wildbower, npm, wildnpm, maven, wildmaven, gradle, wildgradle}


dep-type:
- cocoapods:
  - values:
    - spec
    - version
- wildpods:
  - values:
    - git
    - branch
    - commit
- bower
- wildbower
- npm
- wildnpm
- maven
- wildmaven
- wildgradle


straw-ios-service-http
straw-ios-service-http-js


straw-ios-js
straw-ios
