straw.spec:
- platform: num {ios,android}
- service.topic: string e.g. http
- type: enum {js,native}
- name: straw-{$platform}-{$topic}-service-{$type}

dependecy:
- ios-native:
  - cocoapods
- ios-js:
  - bower
  - npm
- android-native:
  - maven
  - gradle
- android-js:
  - bower
  - npm

straw-ios-service-http-js
straw-ios-service-http-native

straw-ios-native
straw-ios-js
